version: 2
updates:
  # TODO: re-enable when this supports pnpm: https://github.com/dependabot/dependabot-core/issues/1736
  # - package-ecosystem: "npm"
  #   directory: "/"
  #   schedule:
  #     interval: "monthly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
